---

swagger: "2.0"
info:
  version: "1.0"
  title: mts-go-classes-app
  description: API documentation for MTS Go Classes final task

paths:
  /ping:
    get:
      tags:
        - status
      description: Checking if service is available
      responses:
        200:
          description: OK
      produces:
        - "plain/text"

  /users:
    get:
      tags:
        - users
      description: Getting all users
      responses:
        200:
          description: OK
        500:
          description: DB or encoding error
      produces:
        - "application/json"

  /user:
    get:
      tags:
        - users
    put:
      tags:
        - users
    delete:
      tags:
        - users

  /registration:
    post:
      tags:
        - users
      description: Register a new user
      parameters:
        - name: username
          in: query
          description: user's username
          required: true
          type: string
        - name: password
          in: query
          description: user's password
          required: true
          type: string
      responses:
        200:
        400:
        403:
        500:


  /login:
    get:
      tags:
        - users

  /verify:
    get:
      tags:
        - users
