---

swagger: "2.0"
info:
  version: "1.0"
  title: mts-go-classes-app
  description: API documentation for MTS Go Classes final task

paths:
  /ping:
    get:
      tags:
        - status
      description: Checking if service is available
      responses:
        200:
          description: OK
      produces:
        - "plain/text"

  /users:
    get:
      tags:
        - status
      description: Getting all users
      responses:
        200:
          description: OK
        500:
          description: DB or encoding error
      produces:
        - "application/json"

  /user:
    get:
    put:
    delete:

  /registration:
    post:

  /login:
    get:

  /verify:
    get:
